# Basic setting
Sys.setenv(LANGUAGE = 'en')
options(shiny.maxRequestSize = 1000 * 1024^2)

# Load R Package
library(shiny)
# library(shinydashboard)
# library(dashboardthemes)
library(shinyBS)
library(bs4Dash)
library(shinymeta)
library(shinyWidgets)
library(shinycustomloader)
library(tidyverse)
library(gapminder)
library(scales)
library(plotly)
library(viridis)
library(ggthemes)
library(hrbrthemes)
library(ggprism)
library(colourpicker)
library(ggsci)
library(readxl)
library(xts)
library(dygraphs)
library(lubridate)
library(FactoMineR)
library(factoextra)
library(ggforce)
library(ape)
library(vegan)
library(Rtsne)
library(umap)
# library(ggcor)
library(ggrepel)
library(ggsignif)
library(ggbeeswarm)
library(gghalves)
library(gapminder)
library(cowplot)
library(htmltools)
# library(sf)
# library(ggspatial)
library(showtext)
library(highcharter)
library(base64enc)
library(slickR)
library(waiter)
library(ggalt)
library(ggridges)
library(ggradar)
library(ggradar2)
library(treemap)
library(markdown)
library(datasets)

font_families()
showtext_auto()


